export interface Country {
  name: string;
  cities: string[];
}

export const countries: Country[] = [
  { name: 'Afghanistan', cities: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif'] },
  { name: 'Argentina', cities: ['Buenos Aires', 'Córdoba', 'Rosario', 'Mendoza', 'La Plata'] },
  { name: 'Australia', cities: ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Gold Coast', 'Hobart', 'Darwin', 'Canberra'] },
  { name: 'Austria', cities: ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'] },
  { name: 'Bangladesh', cities: ['Dhaka', 'Chittagong', 'Khulna', 'Rajshahi', 'Sylhet'] },
  { name: 'Belgium', cities: ['Brussels', 'Antwerp', 'Ghent', 'Charleroi', 'Liege'] },
  { name: 'Brazil', cities: ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba'] },
  { name: 'Canada', cities: ['Toronto', 'Vancouver', 'Montreal', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton'] },
  { name: 'China', cities: ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xi\'an', 'Chongqing'] },
  { name: 'Colombia', cities: ['Bogotá', 'Medellín', 'Cali', 'Barranquilla', 'Cartagena'] },
  { name: 'Denmark', cities: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg'] },
  { name: 'Egypt', cities: ['Cairo', 'Alexandria', 'Giza', 'Shubra El-Kheima', 'Port Said'] },
  { name: 'France', cities: ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux'] },
  { name: 'Germany', cities: ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Düsseldorf', 'Leipzig', 'Dortmund'] },
  { name: 'Greece', cities: ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa'] },
  { name: 'India', cities: [
    'Agartala', 'Agra', 'Ahmedabad', 'Aizawl', 'Ajmer', 'Akbarpur', 'Aligarh', 'Ambala', 'Amritsar', 'Anantnag', 'Asansol', 'Aurangabad', 'Ayodhya',
    'Bangalore', 'Belgaum', 'Bhilai', 'Bhopal', 'Bhubaneswar', 'Bikaner', 'Bilaspur', 'Bokaro', 'Chandigarh', 'Chennai', 'Coimbatore',
    'Cuttack', 'Dehradun', 'Delhi', 'Dhanbad', 'Dharamshala', 'Dibrugarh', 'Dimapur', 'Durgapur', 'Faizabad', 'Faridabad', 'Gandhinagar', 'Gangtok',
    'Gaya', 'Ghaziabad', 'Gurugram', 'Guwahati', 'Gwalior', 'Haridwar', 'Howrah', 'Hubli', 'Hyderabad', 'Imphal', 'Indore', 'Itanagar',
    'Jabalpur', 'Jaipur', 'Jalandhar', 'Jammu', 'Jamshedpur', 'Jodhpur', 'Jorhat', 'Kanpur', 'Kargil', 'Karimnagar', 'Kochi',
    'Kohima', 'Kolkata', 'Kota', 'Kozhikode', 'Leh', 'Lucknow', 'Ludhiana', 'Madurai', 'Manali', 'Mangalore', 'Margao', 'Meerut',
    'Mohali', 'Mumbai', 'Muzaffarpur', 'Mysore', 'Nagpur', 'Nainital', 'Nashik', 'Nellore', 'New Delhi', 'Nizamabad', 'Noida',
    'Panaji', 'Panipat', 'Patiala', 'Patna', 'Port Blair', 'Prayagraj', 'Puducherry', 'Pune', 'Puri', 'Raipur', 'Rajkot',
    'Ranchi', 'Rohtak', 'Roorkee', 'Rourkela', 'Salem', 'Shillong', 'Shimla', 'Silchar', 'Siliguri', 'Srinagar', 'Sultanpur', 'Surat',
    'Tawang', 'Thane', 'Thiruvananthapuram', 'Thrissur', 'Tirunelveli', 'Tiruchirappalli', 'Udaipur', 'Ujjain', 'Vadodara',
    'Varanasi', 'Vasco da Gama', 'Vijayawada', 'Visakhapatnam', 'Warangal'
  ] },
  { name: 'Indonesia', cities: ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Palembang'] },
  { name: 'Iran', cities: ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz'] },
  { name: 'Italy', cities: ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Venice'] },
  { name: 'Japan', cities: ['Tokyo', 'Osaka', 'Kyoto', 'Sapporo', 'Yokohama', 'Nagoya', 'Kobe', 'Fukuoka', 'Kawasaki'] },
  { name: 'Malaysia', cities: ['Kuala Lumpur', 'George Town', 'Ipoh', 'Shah Alam', 'Petaling Jaya', 'Johor Bahru'] },
  { name: 'Mexico', cities: ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Toluca', 'Tijuana', 'León'] },
  { name: 'Netherlands', cities: ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven'] },
  { name: 'New Zealand', cities: ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga'] },
  { name: 'Nigeria', cities: ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt'] },
  { name: 'Norway', cities: ['Oslo', 'Bergen', 'Trondheim', 'Stavanger'] },
  { name: 'Pakistan', cities: ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Islamabad', 'Multan', 'Peshawar'] },
  { name: 'Philippines', cities: ['Manila', 'Quezon City', 'Davao City', 'Cebu City', 'Zamboanga City'] },
  { name: 'Poland', cities: ['Warsaw', 'Kraków', 'Łódź', 'Wrocław', 'Poznań'] },
  { name: 'Portugal', cities: ['Lisbon', 'Porto', 'Vila Nova de Gaia', 'Amadora'] },
  { name: 'Russia', cities: ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod'] },
  { name: 'Saudi Arabia', cities: ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam'] },
  { name: 'Singapore', cities: ['Singapore'] },
  { name: 'South Africa', cities: ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth'] },
  { name: 'South Korea', cities: ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon'] },
  { name: 'Spain', cities: ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Málaga', 'Murcia', 'Palma'] },
  { name: 'Sri Lanka', cities: ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo'] },
  { name: 'Sweden', cities: ['Stockholm', 'Gothenburg', 'Malmö', 'Uppsala', 'Västerås'] },
  { name: 'Switzerland', cities: ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern'] },
  { name: 'Thailand', cities: ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Nakhon Ratchasima'] },
  { name: 'Turkey', cities: ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Antalya'] },
  { name: 'United Arab Emirates', cities: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman'] },
  { name: 'United Kingdom', cities: ['London', 'Manchester', 'Birmingham', 'Glasgow', 'Liverpool', 'Edinburgh', 'Bristol', 'Leeds'] },
  { name: 'United States', cities: ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'San Francisco', 'Charlotte', 'Indianapolis', 'Seattle', 'Denver', 'Washington', 'Boston'] },
  { name: 'Vietnam', cities: ['Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hai Phong', 'Can Tho'] }
];
